execute as @s[family=s0] at @s run title @p[r=16] actionbar 0
execute as @s[family=s1] at @s run title @p[r=16] actionbar 1
execute as @s[family=s2] at @s run title @p[r=16] actionbar 2
execute as @s[family=s3] at @s run title @p[r=16] actionbar 3
execute as @s[family=s4] at @s run title @p[r=16] actionbar 4
execute as @s[family=s5] at @s run title @p[r=16] actionbar 5
execute as @s[family=s6] at @s run title @p[r=16] actionbar 6
execute as @s[family=s7] at @s run title @p[r=16] actionbar 7
execute as @s[family=s8] at @s run title @p[r=16] actionbar 8
execute as @s[family=s9] at @s run title @p[r=16] actionbar 9
execute as @s[family=s10] at @s run title @p[r=16] actionbar 10
execute as @s[family=s11] at @s run title @p[r=16] actionbar 11
execute as @s[family=s12] at @s run title @p[r=16] actionbar 12
execute as @s[family=s13] at @s run title @p[r=16] actionbar 13
execute as @s[family=s14] at @s run title @p[r=16] actionbar 14
execute as @s[family=s15] at @s run title @p[r=16] actionbar 15
