execute @s[family=s0] ~ ~ ~ title @p[r=16] actionbar 0
execute @s[family=s1] ~ ~ ~ title @p[r=16] actionbar 1
execute @s[family=s2] ~ ~ ~ title @p[r=16] actionbar 2
execute @s[family=s3] ~ ~ ~ title @p[r=16] actionbar 3
execute @s[family=s4] ~ ~ ~ title @p[r=16] actionbar 4
execute @s[family=s5] ~ ~ ~ title @p[r=16] actionbar 5
execute @s[family=s6] ~ ~ ~ title @p[r=16] actionbar 6
execute @s[family=s7] ~ ~ ~ title @p[r=16] actionbar 7
execute @s[family=s8] ~ ~ ~ title @p[r=16] actionbar 8
execute @s[family=s9] ~ ~ ~ title @p[r=16] actionbar 9
execute @s[family=s10] ~ ~ ~ title @p[r=16] actionbar 10
execute @s[family=s11] ~ ~ ~ title @p[r=16] actionbar 11
execute @s[family=s12] ~ ~ ~ title @p[r=16] actionbar 12
execute @s[family=s13] ~ ~ ~ title @p[r=16] actionbar 13
execute @s[family=s14] ~ ~ ~ title @p[r=16] actionbar 14
execute @s[family=s15] ~ ~ ~ title @p[r=16] actionbar 15
