event entity @s[family=s0] "speed_0>1"
event entity @s[family=s1] "speed_1>2"
event entity @s[family=s2] "speed_2>3"
event entity @s[family=s3] "speed_3>4"
event entity @s[family=s4] "speed_4>5"
event entity @s[family=s5] "speed_5>6"
event entity @s[family=s6] "speed_6>7"
event entity @s[family=s7] "speed_7>8"
event entity @s[family=s8] "speed_8>9"
event entity @s[family=s9] "speed_9>10"
event entity @s[family=s10] "speed_10>11"
event entity @s[family=s11] "speed_11>12"
event entity @s[family=s12] "speed_12>13"
event entity @s[family=s13] "speed_13>14"
event entity @s[family=s14] "speed_14>15"
event entity @s[tag=vanilla_actv] vanilla_actv
event entity @s[tag=limit_10] speed_10s
execute as @s[family=s10] at @s if block ~ ~ ~ rail run function minecart_rail_inspector_s10_
